[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "script-src 'self' https://www.vagaro.com 'unsafe-eval'; frame-src 'self' https://www.vagaro.com;"
    X-Frame-Options = "ALLOW-FROM https://www.vagaro.com"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "fullscreen=(self)"